//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decidir_SDK.AuthorizeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.decidir.com.ar", ConfigurationName="AuthorizeService.AuthorizePortType")]
    public interface AuthorizePortType {
        
        // CODEGEN: Parameter 'Session' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="//api.decidir.com.ar/AuthorizePortType/SendAuthorizeRequestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StatusCode")]
        Decidir_SDK.AuthorizeService.SendAuthorizeRequestResponse SendAuthorizeRequest(Decidir_SDK.AuthorizeService.SendAuthorizeRequestRequest request);
        
        // CODEGEN: Parameter 'Session' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="//api.decidir.com.ar/AuthorizePortType/GetAuthorizeAnswerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StatusCode")]
        Decidir_SDK.AuthorizeService.GetAuthorizeAnswerResponse GetAuthorizeAnswer(Decidir_SDK.AuthorizeService.GetAuthorizeAnswerRequest request);
        
        // CODEGEN: Parameter 'Session' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="//api.decidir.com.ar/AuthorizePortType/ExecuteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StatusCode")]
        Decidir_SDK.AuthorizeService.ExecuteResponse Execute(Decidir_SDK.AuthorizeService.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAuthorizeRequest", WrapperNamespace="http://api.decidir.com.ar", IsWrapped=true)]
    public partial class SendAuthorizeRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=0)]
        public string Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=2)]
        public string Merchant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string URL_OK;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string URL_ERROR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EncodingMethod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object Payload;
        
        public SendAuthorizeRequestRequest() {
        }
        
        public SendAuthorizeRequestRequest(string Security, string Session, string Merchant, string URL_OK, string URL_ERROR, string EncodingMethod, object Payload) {
            this.Security = Security;
            this.Session = Session;
            this.Merchant = Merchant;
            this.URL_OK = URL_OK;
            this.URL_ERROR = URL_ERROR;
            this.EncodingMethod = EncodingMethod;
            this.Payload = Payload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAuthorizeRequestResponse", WrapperNamespace="http://api.decidir.com.ar", IsWrapped=true)]
    public partial class SendAuthorizeRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=0)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string URL_Request;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RequestKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PublicRequestKey;
        
        public SendAuthorizeRequestResponse() {
        }
        
        public SendAuthorizeRequestResponse(int StatusCode, string StatusMessage, string URL_Request, string RequestKey, string PublicRequestKey) {
            this.StatusCode = StatusCode;
            this.StatusMessage = StatusMessage;
            this.URL_Request = URL_Request;
            this.RequestKey = RequestKey;
            this.PublicRequestKey = PublicRequestKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthorizeAnswer", WrapperNamespace="http://api.decidir.com.ar", IsWrapped=true)]
    public partial class GetAuthorizeAnswerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=0)]
        public string Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=2)]
        public string Merchant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RequestKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AnswerKey;
        
        public GetAuthorizeAnswerRequest() {
        }
        
        public GetAuthorizeAnswerRequest(string Security, string Session, string Merchant, string RequestKey, string AnswerKey) {
            this.Security = Security;
            this.Session = Session;
            this.Merchant = Merchant;
            this.RequestKey = RequestKey;
            this.AnswerKey = AnswerKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthorizeAnswerResponse", WrapperNamespace="http://api.decidir.com.ar", IsWrapped=true)]
    public partial class GetAuthorizeAnswerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=0)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AuthorizationKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EncodingMethod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object Payload;
        
        public GetAuthorizeAnswerResponse() {
        }
        
        public GetAuthorizeAnswerResponse(int StatusCode, string StatusMessage, string AuthorizationKey, string EncodingMethod, object Payload) {
            this.StatusCode = StatusCode;
            this.StatusMessage = StatusMessage;
            this.AuthorizationKey = AuthorizationKey;
            this.EncodingMethod = EncodingMethod;
            this.Payload = Payload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Execute", WrapperNamespace="http://api.decidir.com.ar", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=0)]
        public string Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=2)]
        public string Merchant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=3)]
        public string Operation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EncodingMethod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object Payload;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string Security, string Session, string Merchant, string Operation, string EncodingMethod, object Payload) {
            this.Security = Security;
            this.Session = Session;
            this.Merchant = Merchant;
            this.Operation = Operation;
            this.EncodingMethod = EncodingMethod;
            this.Payload = Payload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteResponse", WrapperNamespace="http://api.decidir.com.ar", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=0)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AuthorizationKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EncodingMethod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.decidir.com.ar", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object Payload;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(int StatusCode, string StatusMessage, string AuthorizationKey, string EncodingMethod, object Payload) {
            this.StatusCode = StatusCode;
            this.StatusMessage = StatusMessage;
            this.AuthorizationKey = AuthorizationKey;
            this.EncodingMethod = EncodingMethod;
            this.Payload = Payload;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthorizePortTypeChannel : Decidir_SDK.AuthorizeService.AuthorizePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthorizePortTypeClient : System.ServiceModel.ClientBase<Decidir_SDK.AuthorizeService.AuthorizePortType>, Decidir_SDK.AuthorizeService.AuthorizePortType {
        
        public AuthorizePortTypeClient() {
        }
        
        public AuthorizePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthorizePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorizePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorizePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decidir_SDK.AuthorizeService.SendAuthorizeRequestResponse Decidir_SDK.AuthorizeService.AuthorizePortType.SendAuthorizeRequest(Decidir_SDK.AuthorizeService.SendAuthorizeRequestRequest request) {
            return base.Channel.SendAuthorizeRequest(request);
        }
        
        public int SendAuthorizeRequest(string Security, string Session, string Merchant, string URL_OK, string URL_ERROR, string EncodingMethod, object Payload, out string StatusMessage, out string URL_Request, out string RequestKey, out string PublicRequestKey) {
            Decidir_SDK.AuthorizeService.SendAuthorizeRequestRequest inValue = new Decidir_SDK.AuthorizeService.SendAuthorizeRequestRequest();
            inValue.Security = Security;
            inValue.Session = Session;
            inValue.Merchant = Merchant;
            inValue.URL_OK = URL_OK;
            inValue.URL_ERROR = URL_ERROR;
            inValue.EncodingMethod = EncodingMethod;
            inValue.Payload = Payload;
            Decidir_SDK.AuthorizeService.SendAuthorizeRequestResponse retVal = ((Decidir_SDK.AuthorizeService.AuthorizePortType)(this)).SendAuthorizeRequest(inValue);
            StatusMessage = retVal.StatusMessage;
            URL_Request = retVal.URL_Request;
            RequestKey = retVal.RequestKey;
            PublicRequestKey = retVal.PublicRequestKey;
            return retVal.StatusCode;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decidir_SDK.AuthorizeService.GetAuthorizeAnswerResponse Decidir_SDK.AuthorizeService.AuthorizePortType.GetAuthorizeAnswer(Decidir_SDK.AuthorizeService.GetAuthorizeAnswerRequest request) {
            return base.Channel.GetAuthorizeAnswer(request);
        }
        
        public int GetAuthorizeAnswer(string Security, string Session, string Merchant, string RequestKey, string AnswerKey, out string StatusMessage, out string AuthorizationKey, out string EncodingMethod, out object Payload) {
            Decidir_SDK.AuthorizeService.GetAuthorizeAnswerRequest inValue = new Decidir_SDK.AuthorizeService.GetAuthorizeAnswerRequest();
            inValue.Security = Security;
            inValue.Session = Session;
            inValue.Merchant = Merchant;
            inValue.RequestKey = RequestKey;
            inValue.AnswerKey = AnswerKey;
            Decidir_SDK.AuthorizeService.GetAuthorizeAnswerResponse retVal = ((Decidir_SDK.AuthorizeService.AuthorizePortType)(this)).GetAuthorizeAnswer(inValue);
            StatusMessage = retVal.StatusMessage;
            AuthorizationKey = retVal.AuthorizationKey;
            EncodingMethod = retVal.EncodingMethod;
            Payload = retVal.Payload;
            return retVal.StatusCode;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decidir_SDK.AuthorizeService.ExecuteResponse Decidir_SDK.AuthorizeService.AuthorizePortType.Execute(Decidir_SDK.AuthorizeService.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public int Execute(string Security, string Session, string Merchant, string Operation, ref string EncodingMethod, ref object Payload, out string StatusMessage, out string AuthorizationKey) {
            Decidir_SDK.AuthorizeService.ExecuteRequest inValue = new Decidir_SDK.AuthorizeService.ExecuteRequest();
            inValue.Security = Security;
            inValue.Session = Session;
            inValue.Merchant = Merchant;
            inValue.Operation = Operation;
            inValue.EncodingMethod = EncodingMethod;
            inValue.Payload = Payload;
            Decidir_SDK.AuthorizeService.ExecuteResponse retVal = ((Decidir_SDK.AuthorizeService.AuthorizePortType)(this)).Execute(inValue);
            StatusMessage = retVal.StatusMessage;
            AuthorizationKey = retVal.AuthorizationKey;
            EncodingMethod = retVal.EncodingMethod;
            Payload = retVal.Payload;
            return retVal.StatusCode;
        }
    }
}
